services:
  - type: web
    name: medchat-api
    env: python
    plan: free
    buildCommand: "uv sync"
    startCommand: "./start.sh"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000

  - type: web
    name: medchat-ui
    env: python
    plan: free
    buildCommand: "uv sync"
    startCommand: "./start_streamlit.sh"
    envVars:
      - key: BACKEND_URL
        value: "https://medchat-ai.onrender.com"
